# PowerShell script to add Backblaze B2 credentials to .env file
# This script will add or update Backblaze credentials in your .env file

# Script should be run from backend-hono directory
$envFilePath = ".env"

Write-Host "Setting up Backblaze B2 credentials in .env..." -ForegroundColor Green

# Backblaze credentials (provided by user)
$backblazeKeyId = "005f5327cdd9bde0000000001"
$backblazeApplicationKey = "K005MnDtF+uFGMhra2f7PaccZ1aAkg0"
$backblazeBucketName = "anistream-bckt"
$backblazeEndpoint = "https://s3.us-east-005.backblazeb2.com"
$backblazeRegion = "us-east-005"

# Check if .env file exists
if (-not (Test-Path $envFilePath)) {
    Write-Host "Creating .env file..." -ForegroundColor Yellow
    # Create basic .env file with Backblaze config
    $envContent = @"
# Local environment variables for backend-hono
# This file is automatically generated by scripts/backend/setup-backblaze.ps1
# It is ignored by Git (.gitignore)

PORT=8801
NODE_ENV=development

# Backblaze B2 Configuration
BACKBLAZE_KEY_ID=$backblazeKeyId
BACKBLAZE_APPLICATION_KEY=$backblazeApplicationKey
BACKBLAZE_BUCKET_NAME=$backblazeBucketName
BACKBLAZE_ENDPOINT=$backblazeEndpoint
BACKBLAZE_REGION=$backblazeRegion
"@
    $envContent | Out-File -FilePath $envFilePath -Encoding UTF8
    Write-Host "`.env file created with Backblaze credentials!" -ForegroundColor Green
} else {
    Write-Host "Updating existing .env file..." -ForegroundColor Yellow
    
    # Read existing .env content
    $envContent = Get-Content $envFilePath -Raw
    
    # Function to update or add environment variable
    function Update-EnvVar {
        param($name, $value)
        $pattern = "^$name=.*$"
        if ($envContent -match $pattern) {
            # Replace existing
            $envContent = $envContent -replace $pattern, "$name=$value"
            Write-Host "  Updated $name" -ForegroundColor Cyan
        } else {
            # Add new
            $envContent += "`n$name=$value"
            Write-Host "  Added $name" -ForegroundColor Cyan
        }
    }
    
    # Update or add Backblaze variables
    Update-EnvVar "BACKBLAZE_KEY_ID" $backblazeKeyId
    Update-EnvVar "BACKBLAZE_APPLICATION_KEY" $backblazeApplicationKey
    Update-EnvVar "BACKBLAZE_BUCKET_NAME" $backblazeBucketName
    Update-EnvVar "BACKBLAZE_ENDPOINT" $backblazeEndpoint
    Update-EnvVar "BACKBLAZE_REGION" $backblazeRegion
    
    # Write updated content
    $envContent | Out-File -FilePath $envFilePath -Encoding UTF8 -Force
    Write-Host "`.env file updated with Backblaze credentials!" -ForegroundColor Green
}

Write-Host "`nBackblaze B2 credentials configured successfully!" -ForegroundColor Green
Write-Host "You can now test file uploads. Remember to keep your Application Key secure!" -ForegroundColor Yellow
